In [1]:
import pandas as pd

In [2]:
churn=pd.read_csv("../dataset/Churn_Modeling.csv")

In [3]:
churn.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [4]:
churn.shape

(10000, 14)

In [5]:
churn.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
churn.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [7]:
#Removing duplicate data
churn=churn.drop_duplicates()

In [8]:
churn=churn.dropna()

In [9]:
churn.shape

(10000, 14)

In [10]:
val=list(churn.iloc[0].reset_index()[0])
val=[int(val[0]),int(val[1]),val[2],int(val[3]),val[4],val[5],int(val[6]),int(val[7]),float(val[8]),int(val[9]),int(val[10]),int(val[11]),float(val[12]),int(val[13])]
print(val)

[1, 15634602, 'Hargrave', 619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88, 1]

In [11]:
for col in churn.columns:
        print(col,'\t',churn[col].isnull().sum(),'\t',churn[col].dtype)

RowNumber 	 0 	 int64
CustomerId 	 0 	 int64
Surname 	 0 	 str
CreditScore 	 0 	 int64
Geography 	 0 	 str
Gender 	 0 	 str
Age 	 0 	 int64
Tenure 	 0 	 int64
Balance 	 0 	 float64
NumOfProducts 	 0 	 int64
HasCrCard 	 0 	 int64
IsActiveMember 	 0 	 int64
EstimatedSalary 	 0 	 float64
Exited 	 0 	 int64

In [12]:
#Total Balance
print(churn['Balance'].sum())

764858892.88

In [13]:
#Total Salary
print(churn['EstimatedSalary'].sum())

1000902398.8100001

In [14]:
#Average Salary
print(churn['EstimatedSalary'].mean())

100090.239881

In [15]:
#Average Credit Score
print(churn['CreditScore'].mean())

650.5288

In [16]:
#Region wise Products
print(churn.groupby('Geography')['NumOfProducts'].sum())

Geography
France     7676
Germany    3813
Spain      3813
Name: NumOfProducts, dtype: int64

In [17]:
#Best Customer
print(churn.groupby('Surname')['NumOfProducts'].sum().sort_values(ascending=False).head(5))

Surname
Smith     52
Walker    48
Scott     44
Martin    43
Wright    40
Name: NumOfProducts, dtype: int64

In [18]:
#Highest Product Purchase region
print(churn.groupby('Geography')['NumOfProducts'].sum().idxmax())

France

In [19]:
#Maximum Credit score
print(churn.groupby('Surname')['CreditScore'].sum().sort_values(ascending=False).head(3))

Surname
Smith     21215
Martin    19797
Walker    18597
Name: CreditScore, dtype: int64

In [20]:
#Minimum Credit Score
print(churn.groupby('Surname')['CreditScore'].sum().sort_values(ascending=True).head(5))

Surname
Aikenhead    358
Pike         386
McMasters    399
Loftus       401
Hickey       408
Name: CreditScore, dtype: int64

In [21]:
#Maximum Active Members
print(churn.groupby('Geography')['IsActiveMember'].sum())

Geography
France     2591
Germany    1248
Spain      1312
Name: IsActiveMember, dtype: int64

In [22]:
churn.reset_index()

,index,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0